# Generated by Django 5.0.1 on 2024-02-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0003_space'),
    ]

    operations = [
        migrations.CreateModel(
            name='MEKItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('header', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='XYItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('header', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='space',
            name='category',
        ),
        migrations.DeleteModel(
            name='blog',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='space',
        ),
    ]
